# **Python final project**

##**Student info**

**Name:** Sander van der Graaf 

**Student id:** 6210266

##**Assignment info**

In [ ]:
#assignment

#deadline = 9th of february 9:00 am

#more info on the covid dataset: https://github.com/owid/covid-19-data/tree/master/public/data

#introduction (5 pt):
#Formulate a research question that allows for explorations and comparisons. 
#For example: How have vaccinations influenced hospitalizations in different European Union (EU) countries? 
#You can divide this in two steps: 
# 1. How vaccinations have influenced hospitalizations in a country (i.e Netherlands or Italy); 
# 2. How does one country compare to the other countries in the EU?

#data preparation:
#Load the dataset using this link. Copy the link and load it as you did in the practicals. (5 pt)
#Select rows and columns relevant to your research question. (15 pt)

#explore and clean the data by:
#Explore those data using descriptive statistics or visualisations to get to know the dataset and spot possible issues (such as outliers or typos)(10 pt)
#Identify and report issues with missing data. (5 pt)
#Resolve issues with missing data and clean other data inconsistencies. Report also if you found no issues and how you verified this. (5 pt)

#describe and visualise:
#Provide a description of the population for the reader (e.g. countries or continents) relevant to your question using a table with descriptive statistics (i.e. means, medians, standard deviations) and where possible visualisation. (15pt)
#Make the report interactive: Create at least one interactive visualisation using input from the user. (20pt)
#Turn your interactive report into an application using GitHub, Voila and Binder. (15pt)

#conclusion (5 pt):
#Summarise the work and the main findings related to the initial research question. (5 pt)

##Code

In [ ]:
#imports (pandas)
#covid data import

import pandas as pd

covid = pd.read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv", parse_dates=['date'])

covid.head()

  iso_code continent  ... excess_mortality excess_mortality_cumulative_per_million
0      AFG      Asia  ...              NaN                                     NaN
1      AFG      Asia  ...              NaN                                     NaN
2      AFG      Asia  ...              NaN                                     NaN
3      AFG      Asia  ...              NaN                                     NaN
4      AFG      Asia  ...              NaN                                     NaN

[5 rows x 67 columns]